// Find all input fields in the DOM
function getFormFields() {
  const inputs = document.querySelectorAll('input:not([type="hidden"]):not([type="submit"]):not([type="button"]), textarea, select');
  return Array.from(inputs);
}

// Highlight the detected fields
function highlightFields() {
  const fields = getFormFields();
  fields.forEach(field => {
    // Add a glowing purple border to indicate AI detection
    field.style.transition = 'all 0.3s ease';
    field.style.border = '2px solid #7342E2';
    field.style.boxShadow = '0 0 8px rgba(115, 66, 226, 0.5)';
    field.style.backgroundColor = 'rgba(115, 66, 226, 0.05)';
  });
}

// Mock autofill logic for prototype
function mockAutofill() {
  const fields = getFormFields();
  
  fields.forEach(field => {
    // Simple heuristic to fill fields based on common name attributes
    const name = (field.name || field.id || '').toLowerCase();
    const type = field.type;
    
    if (type === 'checkbox' || type === 'radio') {
      // randomly check some boxes if needed, or leave alone for now
      return;
    }
    
    if (name.includes('first') || name.includes('name')) {
      field.value = "John Doe";
    } else if (name.includes('email')) {
      field.value = "johndoe@example.com";
    } else if (name.includes('phone') || name.includes('tel')) {
      field.value = "+62 812 3456 7890";
    } else if (name.includes('job') || name.includes('title') || name.includes('position')) {
      field.value = "Senior Software Engineer";
    } else if (name.includes('company') || name.includes('employer')) {
      field.value = "Tech Solutions Inc.";
    } else if (name.includes('linkedin')) {
      field.value = "https://linkedin.com/in/johndoe";
    } else if (name.includes('github')) {
      field.value = "https://github.com/johndoe";
    } else if (field.tagName.toLowerCase() === 'textarea' || name.includes('summary') || name.includes('cover')) {
      field.value = "I am a highly motivated software engineer with 5+ years of experience in building scalable web applications. I am excited about this opportunity.";
    } else {
      // Default fallback
      field.value = "Generated by ApplyFlow AI";
    }
    
    // Trigger input and change events so modern JS frameworks (React/Vue) detect the change
    field.dispatchEvent(new Event('input', { bubbles: true }));
    field.dispatchEvent(new Event('change', { bubbles: true }));
    
    // Visually indicate it was filled by AI
    field.style.backgroundColor = '#ecfdf5'; // light emerald
    field.style.border = '2px solid #10B981'; // emerald green
    field.style.boxShadow = '0 0 8px rgba(16, 185, 129, 0.3)';
  });
}

// Listen for messages from popup
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === 'COUNT_FIELDS') {
    const count = getFormFields().length;
    sendResponse({ count: count });
  } else if (request.action === 'HIGHLIGHT_FIELDS') {
    highlightFields();
    sendResponse({ success: true });
  } else if (request.action === 'MOCK_AUTOFILL') {
    mockAutofill();
    sendResponse({ success: true });
  }
  return true; // Keep message channel open for async response
});
